#include <bits/stdc++.h>
using namespace std;

using ll = long long;
using i128 = __int128_t;

struct Line {
    ll m, b;

    ll value(ll x) const {
        return m * x + b;
    }
};

// Check whether l2 is unnecessary.
// Slopes are inserted in decreasing order.
bool bad(const Line& l1, const Line& l2, const Line& l3) {
    return (i128)(l2.b - l1.b) * (l2.m - l3.m)
         >= (i128)(l3.b - l2.b) * (l1.m - l2.m);
}

int main() {
    int n;
    ll w;

    cin >> n >> w;

    vector<ll> energy(n + 1);

    for (int i = 1; i <= n; i++) {
        cin >> energy[i];
    }

    vector<ll> dp(n + 1);

    dp[1] = energy[1];

    deque<Line> hull;

    // Line generated by j = 1
    hull.push_back({
        -2LL * w * 1,
        dp[1] + w * 1LL * 1
    });

    for (ll i = 2; i <= n; i++) {

        // Queries x are increasing, so remove worse lines.
        while (hull.size() >= 2 &&
               hull[0].value(i) >= hull[1].value(i)) {
            hull.pop_front();
        }

        ll best = hull.front().value(i);

        dp[i] = energy[i] + w * i * i + best;

        // New line generated by current i
        Line current = {
            -2LL * w * i,
            dp[i] + w * i * i
        };

        // Maintain convex hull.
        while (hull.size() >= 2 &&
               bad(hull[hull.size() - 2],
                   hull[hull.size() - 1],
                   current)) {
            hull.pop_back();
        }

        hull.push_back(current);
    }

    cout << dp[n] << '\n';

    return 0;
}
